@startuml InventoryPanel
control ServerSystem as ServerSystem
control ClientSystem as ClientSystem
control ModUIManager as ModUIManager
boundary UIScreen as UIScreen
boundary InventoryPanel as InventoryPanel

group 背包变动 -> 界面更改
    ServerSystem -> ServerSystem: 游戏内触发事件:\n 1.打开包含 InventoryPanel 的界面 \n 2.ActorAcquiredItemServerEvent 事件
    activate ServerSystem
    ServerSystem -> ServerSystem: 回调函数:UpdateBagUI \n 获取数据:list(items), blockName
    ServerSystem -> ClientSystem: 发送事件与数据到客户端
    deactivate ServerSystem
    activate ClientSystem
    ClientSystem -> ClientSystem: 回调函数:\nOnBagChanged
    ClientSystem -> ModUIManager: 尝试获取 UI 结点
    activate ModUIManager
    alt UI 未创建
        ModUIManager -> ModUIManager: UI　初始化
        ModUIManager -> UIScreen: 创建 UI 结点并返回
        activate UIScreen
    else UI 已创建
        ModUIManager -> UIScreen: 返回 UI 结点
        deactivate ModUIManager
    end
    UIScreen -> InventoryPanel: 调用 BagUIChanged \n刷新 UI 界面 
    deactivate UIScreen
    deactivate ClientSystem
end
group 界面更改 -> 背包变动
    InventoryPanel -> InventoryPanel: 触发界面变动事件\n 获取 list(items), playerId数据\n 向服务端发送事件与数据
    activate InventoryPanel
    InventoryPanel -> ServerSystem: 调用 BagUIChanged 函数，对背包进行刷新
end
@enduml